name: justorder
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.8
  my_ui:
    path: /Users/art_mac/FlutterProjs/Templates/my_ui
  flutter_styled_toast: ^2.2.1
  flutter_riverpod: ^3.0.0 #^2.6.1
  network_info_plus: ^7.0.0
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  uuid: ^4.5.1
  package_info_plus: ^9.0.0
  device_info_plus: ^12.1.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  local_auth: ^2.3.0
  progress_border: ^0.1.5
  audioplayers: ^6.5.1
  transparent_image: ^2.0.1
  sticky_headers: ^0.3.0+2
  uri_to_file:
    path: /Users/art_mac/FlutterProjs/ThirdParty/uri-to-file-main
  image_editor_plus: #^1.0.6
    path: /Users/art_mac/FlutterProjs/ThirdParty/image_editor_plus-main
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  image_picker: ^1.2.0
  flutter_popup: ^3.3.9
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  path: ^1.9.1
  url_launcher: ^6.3.2
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  envied: ^1.3.0
  promptpay_qrcode_generate: ^1.0.2
  badges: ^3.1.2
  scrollable_list_tab_scroller: ^3.1.1
  animated_emoji: ^3.2.1
  # flutter_beep: ^1.0.0
  collection: ^1.19.1
  barcode_scan2: ^4.5.1
  # flutter_beep_plus: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  envied_generator: ^1.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
    - assets/files/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Regular.ttf
    - family: CSChatThaiUI
      fonts:
        - asset: assets/fonts/CSChatThaiUI.ttf
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
